### ISSUE TITLE
Individual proxy for each accounts

### ISSUE THREAD

**Issue by lybimiy86** [csgofloat/CSGOFloat-Inspect#57]
Is it possible to use proxy servers for accounts?
It would be great if we could ask them in this section.
        {
            'user': 'user',
            'pass': 'proxy',
            //'auth': '2FA_TOKEN_2',
           'proxy': ''
        },

**Comment by Step7750** [comment]
Why would you?

**Comment by lybimiy86** [comment]
After about 4000 requests from different accounts, but from one ip - I get an error:
{"error":"Valve's servers appear to be offline, please try again later","code":5}
When i connect vpn and its work again. After about 4000 request i have whis error again, change vpn server and work.

**Comment by Step7750** [comment]
What are you referring to with "requests"? Bot logins or float requests?

**Comment by lybimiy86** [comment]
float requests

**Comment by Step7750** [comment]
How many accounts? Over what time period?

**Comment by Step7750** [comment]
You can login _thousands_ of accounts on a single IP,  so I don't see what your issue would be besides network conditions.

**Comment by lybimiy86** [comment]
im used 100 accounts, Ok, I will try to use 500 accounts. Do all your accounts work on the same ip?

**Comment by Step7750** [comment]
You shouldn't need more accounts. I'm just saying that it is likely due to CM peering and Valve's maintenance.

**Comment by olehsamoilenko** [comment]
Hi @Step7750 
I've found this issue because I was searching an info about how safety it is to make many requests from 1 account. May steam regard that it's malicious activity or something similar? 
For example, I have single account and make a request every second. 
May I be banned and how can I protect myself?
Thank you

**Comment by Step7750** [comment]
Considering this is the current recommended method by Valve's developer wiki to fetch item data, you likely won't be banned. You may reach rate limits however.
