### ISSUE TITLE
s-parameter

### ISSUE THREAD

**Issue by ValvojaX** [csgofloat/CSGOFloat-Inspect#65]
I noticed that calling
https://api.csgofloat.com/?s=76561202255233013&a=18939970445&d=3207337044034781329
gives results but calling
http://localhost/?s=76561202255233013&a=18939970445&d=3207337044034781329
just times out

Then I noticed that it works with my steamid, but changing s-parameter to anything doesn't matter with api.csgofloat but changing it on localhost makes it not work.

For example:
(both work)
https://api.csgofloat.com/?s=76561202255233013&a=18939970445&d=3207337044034781329
https://api.csgofloat.com/?s=76561202255233012&a=18939970445&d=3207337044034781329

(works)
https://api.csgofloat.com/?s=76561198325072791&a=18939970445&d=3207337044034781329
(doesn't work)
https://api.csgofloat.com/?s=76561198325072792&a=18939970445&d=3207337044034781329

**Comment by Step7750** [comment]
That's because our cache is keyed on solely the asset id (which for some market items isn't the best judgement since Steam makes some strange reuse optimizations). So you could effectively make s or d param whatever you want if we already have the item cached.
