### ISSUE TITLE
How can I specify steam servers?

### ISSUE THREAD

**Issue by HiXinJ** [csgofloat/CSGOFloat-Inspect#68]
How can I specify steam CM servers in configuration file?  

https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?format=json&cellid=0

**Comment by Step7750** [comment]
This would be under the node-steam-user settings, which you can try passing in the config. I don't know if they support that for sure, or what type of peering it does other than just fetching the CMList itself.
