### ISSUE TITLE
{error: "Valve's servers appear to be offline, please try again later", code: 5}

### ISSUE THREAD

**Issue by ValvojaX** [csgofloat/CSGOFloat-Inspect#69]
Got this error when I ran index.js on linux server, any workaround?

**Comment by Step7750** [comment]
I'll need more details about your environment, what steps you took, how many bot accounts you have, your logs, etc...

**Comment by ValvojaX** [comment]
I'm using Scaleway linux server, I have 10 bots running, I ran the file in tmux so it won't close after I leave the server. I tested on my local PC and it worked fine, I moved the stuff on the server and it gives that error. Here are the logs when I start (putty doesn't show full logs, only the last x amount of lines):

debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Logging in ***** 
debug: ***** About to connect
info: Listening for HTTP on port: 88
debug: Fetched items_game_cdn.txt
debug: Fetched schema.json
debug: Fetched items_game.txt
debug: Fetched csgo_english.txt

**Comment by Step7750** [comment]
There is likely something wrong about your server environment causing it to fail connecting to the Steam CM and CS:GO GC.

**Comment by ValvojaX** [comment]
Update: I made new steam accounts and put them in a config file, now it works on the server. I have no steam guard on none of the accounts, but could it be steam asking for email confirmation because of login from new device?

**Comment by ValvojaX** [comment]
Update: I also noticed that after index.js has been running for a while, it fails to get the details with error {"error":"Valve's servers didn't reply in time","code":4}, after restarting it works again. How to fix?

**Comment by Step7750** [comment]
See #70
