### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by yeich** [csgofloat/CSGOFloat-Inspect#74]
Hey,

i just tried the beta version of the API.
Sadly, i get following error, everytime i try to make an Inspect Request to the / Route.

`(node:14868) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432                                                                                                                                                        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)                                                                                                                                                                          (node:14868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

Node Version: 12
OS: Windows / Mac

Does anyone now where the issue is coming from?

Cheers,
Yannick

**Comment by Step7750** [comment]
The beta branch requires a postgres connection set in the config which is the issue you're seeing. The config has been clarified.
