### ISSUE TITLE
Bots won't login

### ISSUE THREAD

**Issue by Andreas2200** [csgofloat/CSGOFloat-Inspect#75]
I'm trying to log in 2 bots, but it keeps on returning invalid password.
The thing is that if I copy the login details from the config.js file directly into steam I can log into the bot without problem.

This is the log I get

`{"level":"info","message":"Logging in #####","timestamp":"2020-08-20T10:29:52.544Z"}`

`{"level":"info","message":"Logging in #####","timestamp":"2020-08-20T10:29:52.551Z"}`

`{"message":"Error logging in #####:","stack":"Error: InvalidPassword\n    at SteamUser._handlers.(anonymous function) (/usr/src/csgofloat/node_modules/steam-user/components/logon.js:363:16)\n    at SteamUser._handleMessage (/usr/src/csgofloat/node_modules/steam-user/components/messages.js:249:30)\n    at CMClient.emit (events.js:203:15)\n    at CMClient._netMsgReceived (/usr/src/csgofloat/node_modules/steam-client/lib/cm_client.js:323:8)\n    at CMClient.handlers.(anonymous function) (/usr/src/csgofloat/node_modules/steam-client/lib/cm_client.js:609:8)\n    at CMClient._netMsgReceived (/usr/src/csgofloat/node_modules/steam-client/lib/cm_client.js:305:24)\n    at TCPConnection.emit (events.js:198:13)\n    at TCPConnection._readPacket (/usr/src/csgofloat/node_modules/steam-client/lib/tcp_connection.js:183:7)\n    at Socket.emit (events.js:198:13)\n    at emitReadable_ (_stream_readable.js:554:12)","eresult":5,"level":"error","timestamp":"2020-08-20T10:29:54.025Z"}`

`{"message":"Error logging in #####:","stack":"Error: InvalidPassword\n    at SteamUser._handlers.(anonymous function) (/usr/src/csgofloat/node_modules/steam-user/components/logon.js:363:16)\n    at SteamUser._handleMessage (/usr/src/csgofloat/node_modules/steam-user/components/messages.js:249:30)\n    at CMClient.emit (events.js:203:15)\n    at CMClient._netMsgReceived (/usr/src/csgofloat/node_modules/steam-client/lib/cm_client.js:323:8)\n    at CMClient.handlers.(anonymous function) (/usr/src/csgofloat/node_modules/steam-client/lib/cm_client.js:609:8)\n    at CMClient._netMsgReceived (/usr/src/csgofloat/node_modules/steam-client/lib/cm_client.js:305:24)\n    at TCPConnection.emit (events.js:198:13)\n    at TCPConnection._readPacket (/usr/src/csgofloat/node_modules/steam-client/lib/tcp_connection.js:183:7)\n    at Socket.emit (events.js:198:13)\n    at emitReadable_ (_stream_readable.js:554:12)","eresult":5,"level":"error","timestamp":"2020-08-20T10:29:54.032Z"}`

I've also gotten the program to print the login details to the log so I could verify it was the correct information it got, and it all was correct.

**Comment by BrodyCloud** [comment]
If the bots don't need 2FA or simply new account in general make sure in config.js that
`'auth': ''"`

**Comment by Step7750** [comment]
I haven't been able to reproduce this, do these bots have 2FA? Feel free to re-open with more details.
