### ISSUE TITLE
Sticker wear

### ISSUE THREAD

**Issue by dennissimmo** [csgofloat/CSGOFloat-Inspect#79]
Hi, can you add parathemer "wear" for sticker , when returning json from inpect url by example "https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198984091613A19282557712D11880652775751478859"
Simple add another field named wear, which will return value [0,100] or it is unreal?
Thank you!

**Comment by Step7750** [comment]
If the sticker has wear, it'll show up in the `wear` property. https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M3279140251008183621A19480249543D2499016526748371449
