### ISSUE TITLE
JSON does not include sticker's %

### ISSUE THREAD

**Issue by daslanis** [csgofloat/CSGOFloat-Inspect#83]
I am looking for an easy way to analyse an inspect link without having to open csgo or generate a screenshot... I just need a JSON and while your script does the job, it does not include the sticker's % :/

**Comment by andruszkow** [comment]
Sticker wear is returned if there's a value for it, i.e. 0.63.

Wear will not be returned if the sticker is unscraped

**Comment by Step7750** [comment]
Like @andruszkow said, if there is wear, it'll show it in the sticker attribute.

Here's an example: https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M4660643720973168853A22657417285D9711456941047850395

`[{"stickerId":4789,"slot":0,"wear":0.6906866431236267,"codename":"rmr2020_team_ren","material":"rmr2020/ren","name":"Renegades | 2020 RMR"}]`
