### ISSUE TITLE
killeatervalue and customname both are broken in the reply JSON

### ISSUE THREAD

**Issue by cheddy1** [csgofloat/CSGOFloat-Inspect#84]
When getting a reply from the API for an item with either stattrak or a nametag, it seems like neither reply actually works. For the following skin;

steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198269207545A16664606974D16288577316842925439

We can see that `"killeatervalue":0`, but it should be 16208. The skin also has a nametag, but it seems that the `customname` is missing all together.

```
{"iteminfo":{"origin":4,"quality":9,"rarity":5,"a":"16664606974","d":"2909510241188187007","paintseed":389,"defindex":7,"paintindex":282,"stickers":[{"stickerId":4339,"slot":0,"wear":0.6896421313285828,"codename":"berlin2019_signature_sico","material":"berlin2019/sig_sico","name":"Sico | Berlin 2019"},{"stickerId":2780,"slot":1,"codename":"boston2018_signature_olofmeister","material":"boston2018/sig_olofmeister","name":"olofmeister | Boston 2018"},{"stickerId":2316,"slot":2,"codename":"krakow2017_signature_nothing","material":"krakow2017/sig_nothing","name":"n0thing | Krakow 2017"},{"stickerId":2692,"slot":3,"codename":"boston2018_signature_nbk_gold","material":"boston2018/sig_nbk_gold","name":"NBK- (Gold) | Boston 2018"}],"killeatervalue":0,"floatvalue":0.26375874876976013,"s":"76561198269207545","m":"0","imageurl":"http://media.steampowered.com/apps/730/icons/econ/default_generated/weapon_ak47_cu_ak47_cobra_light_large.7494bfdf4855fd4e6a2dbd983ed0a243c80ef830.png","min":0.1,"max":0.7,"weapon_type":"AK-47","item_name":"Redline","rarity_name":"Classified","quality_name":"StatTrak™","origin_name":"Crafted","wear_name":"Field-Tested","full_item_name":"StatTrak™ AK-47 | Redline (Field-Tested)"}}
```

**Comment by Step7750** [comment]
For `nametag`, this has been broken by Valve for years, the proto response doesn't contain it (try inspecting the gun in-game, the nametag won't show up).

For `killeatervalue`, this isn't retained in the database, so responses will typically omit this unless it was the first time the item was fetched. This was considered to be a low-value attribute not worth storing in a database with persistence. If you're hosting an instance yourself, you can tweak this as you wish.
