### ISSUE TITLE
how to get param

### ISSUE THREAD

**Issue by gitdust** [csgofloat/CSGOFloat-Inspect#93]
hello there,

steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S%owner_steamid%A%assetid%D16321860215213409153

this is one of my csgo item link got from steam api and i know s param is 76561202255233023,but what is a/d/m param ?

**Comment by mertolbekirov** [comment]
Hi. I'm having a similar issue. I have this inspect link given from steam and I can't manage to use it with csgofloat's public api. Have you managed to solve the problem?

**Comment by Step7750** [comment]
You'll need to replace `%owner_steamid%` `%assetid` yourself from wherever you're fetching these links. This is unrelated to this repositoy.

**Comment by gitdust** [comment]
sorry for later response, much thxs @Step7750
