### ISSUE TITLE
/bulk request failing (Bad Secret)

### ISSUE THREAD

**Issue by mertolbekirov** [csgofloat/CSGOFloat-Inspect#94]
Hi, im trying to create a bulk request with this json: https://pastebin.com/1jmAWyxw. The content type is correct and the json is correct but I keep receiving Error 8 Bad Secret. 

The endpoint im sending a post req to: https://api.csgofloat.com/bulk
Content-type: application-json
Body: https://pastebin.com/1jmAWyxw

**Comment by Step7750** [comment]
The bulk endpoint is not intended for public use, this error is expected. Please host the repository yourself if you want to use this feature.
