### ISSUE TITLE
No response when inspecting link.

### ISSUE THREAD

**Issue by checklx** [csgofloat/CSGOFloat-Inspect#96]
I still get a response when get http://127.0.0.1/stats

{"bots_online":1,"bots_total":1,"queue_size":0,"queue_concurrency":1}

But when I get or post: 
http://127.0.0.1/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M625254122282020305A6760346663D30614827701953021

The status is as shown in the picture, the status is always "Sending request"
![image](https://user-images.githubusercontent.com/50614010/127696128-2a64d6e4-95ab-49b8-ae88-e28be0028eb4.png)

Console log
![image](https://user-images.githubusercontent.com/50614010/127696315-46ce347d-6d76-4d0c-8fb4-9e063c6070cf.png)

**Comment by JesseBusman** [comment]
Same problem

**Comment by JesseBusman** [comment]
In my case it got stuck on:

    const itemData = await postgres.getItemData(job.getRemainingLinks().map(e => e.link));

**Comment by Step7750** [comment]
You need to configure a postgresql instance and set it here: https://github.com/csgofloat/CSGOFloat-Inspect/blob/master/config.example.js#L60

**Comment by checklx** [comment]
@JesseBusman @Step7750 
I solved it, the problem was in the pq version not compatible with Nodejs.
https://github.com/brianc/node-postgres/issues/2180

**Comment by sludgefudge01** [comment]
Sorry to open this again but I am facing the same issue. 

This is the postgres db url I am using 
<img width="1070" alt="Screen Shot 2021-12-21 at 11 29 33 PM" src="https://user-images.githubusercontent.com/63462723/146977020-17afd70f-cf1f-4755-92cc-869be2560b35.png">

pgadmin 4 screenshot.
<img width="1440" alt="Screen Shot 2021-12-21 at 11 25 21 PM" src="https://user-images.githubusercontent.com/63462723/146976468-1423f9f4-cf58-446f-8cf0-3213eeed2ab4.png">

I set the password for the postgres user and port isdefault at 5432 

am I missing something here? I am new to Postgres. Help is appreciated, thanks!
